// <auto-generated/> 由脚本从 B站分区接口(app.bilibili.com/x/v2/region/index)生成,
// 只保留"与视频相关"的一级分区(2026-09-26 用户要求精简掉 专栏/直播/漫画/游戏中心 这类非视频项),
// Tid 供原生分区页走 ranking/v2?rid= 接口。番剧/国创 的 rid 不被 ranking/v2 接受(实测 -400), 一并去掉。
// IconUrl 为空 = 官方接口没给图标, UI 用首字色块兜底。
namespace BiliDesk.Services;

/// <summary>分区面板里的一项(IconUrl 可能为空)。</summary>
public sealed record PartitionItem(string Name, int Tid, string IconUrl)
{
    /// <summary>没有官方图标时, 兜底色块上显示的首字</summary>
    public string Initial => string.IsNullOrEmpty(Name) ? "" : Name[..1];
}

/// <summary>首页左上角 logo 展开的分区面板数据。</summary>
public static class PartitionCatalog
{
    public static readonly IReadOnlyList<IReadOnlyList<PartitionItem>> Columns =
        new[] {
            new PartitionItem[] {
                new("电影", 23, "https://i0.hdslb.com/bfs/archive/137edde9deb7dfcdf610ed2d1ec63bae6ef3ba0a.png"),
                new("动画", 1, "https://i0.hdslb.com/bfs/archive/9b3bb8cfc8d87809ffa409bc65def8d8c3eaf72b.png"),
                new("音乐", 3, "https://i0.hdslb.com/bfs/archive/3a99c51d00038ced3989686b6f3c49d01aa34207.png"),
                new("娱乐", 5, "https://i0.hdslb.com/bfs/archive/a9bcb4cb7e216c2ea28ba3dc10acd2d210f739bd.png"),
                new("资讯", 202, "https://i0.hdslb.com/bfs/legacy/d71e70e1bfcb7b27ffe88e6cb82868c68b084464.png"),
                new("时尚美妆", 155, "https://i0.hdslb.com/bfs/archive/1842562be5ded346d79312b24fafedbc1d78c8e2.png"),
                new("生活", 160, "https://i0.hdslb.com/bfs/archive/50731fc4b9ec487ef2e3861a97e0eb4671b7bcef.png"),
            },
            new PartitionItem[] {
                new("电视剧", 11, "https://i0.hdslb.com/bfs/archive/30779a6904875754762e666b7076014528ef4834.png"),
                new("游戏", 4, "https://i0.hdslb.com/bfs/archive/9c88ce1adaecf31e27121bdbb5a29824d655d0a6.png"),
                new("舞蹈", 129, "https://i0.hdslb.com/bfs/archive/4769a6faa9ccfde4a029eca36b979bac486afd14.png"),
                new("知识", 36, "https://i0.hdslb.com/bfs/archive/d5bb279936dbe661f958683231566214056987b2.png"),
                new("美食", 211, "https://i0.hdslb.com/bfs/archive/0f5e21f08616f9c02d706433ba1c00bd5b889c7b.png"),
                new("体育运动", 234, "https://i0.hdslb.com/bfs/feed-admin/56a67fa38d8d7378ab4154307d26cffce2d1ae3f.png"),
            },
            new PartitionItem[] {
                new("纪录片", 177, "https://i0.hdslb.com/bfs/archive/884a644c6bb4b8bb16f9746ef35fbaba396e0b8c.png"),
                new("鬼畜", 119, "https://i0.hdslb.com/bfs/archive/de50290b11c65108eb70766fa887032b948d2e4b.png"),
                new("影视", 181, "https://i0.hdslb.com/bfs/archive/f90bb1ef59630ad9765486c6088a4944b96e88a3.png"),
                new("科技数码", 188, "https://i0.hdslb.com/bfs/feed-admin/4a687a86b49feea68d423fd1bf2c461acfe59b70.png"),
                new("汽车", 223, "https://i0.hdslb.com/bfs/feed-admin/1515d944550494abf81b552a84484dce80287242.png"),
                new("动物圈", 217, "https://i0.hdslb.com/bfs/archive/9f3303b20e12ac874c379da09bca9ce4d0b2f88c.png"),
            },
        };
}
